### ISSUE TITLE
Make AUR packages conflict with community package

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1026]
Currently for example https://aur.archlinux.org/packages/wezterm-git/ does not  conflict with https://archlinux.org/packages/community/x86_64/wezterm/

**Comment by wez** [comment]
@gaborbernat: would you mind taking a look at this?

**Comment by gaborbernat** [comment]
Sure 👍

**Comment by gaborbernat** [comment]
Done https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wezterm-git#n24

**Comment by juligreen** [comment]
This is still an issue with the `wezterm-nightly-bin` package

**Comment by wez** [comment]
Done: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wezterm-nightly-bin#n11
