### ISSUE TITLE
Pasting sometimes does not work correctly

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1296]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211002-212547-9a787549

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Sometimes pasting does not work correctly and pastes an old value. While other applications paste the correct value.
This might be related to using OSC 52, but I could not reliably reproduce it.

### Configuration

no config

**Comment by wez** [comment]
There's not enough information here to reproduce this; can you distill this down to the smallest set of steps/config necessary to get it to trigger?

**Comment by ModProg** [comment]
> There's not enough information here to reproduce this; can you distill this down to the smallest set of steps/config necessary to get it to trigger?

Well I normally notice it using nvim because that's where I paste most. And is solved as soon as I copy something inside wezterm, meaning if I notice I am pasting some old value, I copy a random string in wezterm, then copy the original thing from e.g. Firefox, and then I can paste in wezterm the correct thing.

The whole time pasting elsewhere works, e.g. using `"+p` in nvim

**Comment by wez** [comment]
I'm still not clear on the steps needed to reproduce this; if you can get a reliable repro then please re-open this with that information!

**Comment by ModProg** [comment]
Alright, I'm not sure myself as I could not reliably reproduce it. But I know it is happening. I'll stay with the `"+p` for now.

**Comment by ettoredn** [comment]
I am experiencing similar issues, but instead the pasted text is being stripped from newlines and **overwrites** existing text inside a shell running the nano editor.

**Comment by ModProg** [comment]
@wez anything I should try to do to get more information if it happens the next time?

**Comment by wez** [comment]
@ModProg I need to know how to reproduce the problem, otherwise I have no idea what's actually going wrong or where :-/

**Comment by ettoredn** [comment]
Version: `20220101-133340-7edc5b5a`

```
local wezterm = require 'wezterm';

return {
	audible_bell = "Disabled",
	initial_cols = 134,
	initial_rows = 30,
	enable_scroll_bar = true,
	scrollback_lines = 10000,
	-- debug_key_events = true,
	window_padding = {top = 0, bottom = 0, left = 4, right = 4},

	keys = {
		{key="k", mods="CMD", action=wezterm.action{ClearScrollback="ScrollbackAndViewport"}},
		{key="s", mods="CMD", action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
		{key="s", mods="CMD|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
		{key="Enter", mods="CMD", action="ToggleFullScreen"},
		{key="l", mods="ALT", action="ShowLauncher"},
	    {key="UpArrow", mods="SHIFT", action=wezterm.action{ScrollToPrompt=-1}},
    	{key="DownArrow", mods="SHIFT", action=wezterm.action{ScrollToPrompt=1}},
    	{key="LeftArrow", mods="CMD", action=wezterm.action{ActivatePaneDirection="Left"}},
    	{key="RightArrow", mods="CMD", action=wezterm.action{ActivatePaneDirection="Right"}},
    	{key="UpArrow", mods="CMD", action=wezterm.action{ActivatePaneDirection="Up"}},
		{key="DownArrow", mods="CMD", action=wezterm.action{ActivatePaneDirection="Down"}},
		{key="w", mods="CMD", action=wezterm.action{CloseCurrentPane={confirm=false}}},
		{key="w", mods="CMD|SHIFT", action=wezterm.action{CloseCurrentTab={confirm=true}}},
		{key="[", mods="CMD", action=wezterm.action{ActivateTabRelative=-1}},
    	{key="]", mods="CMD", action=wezterm.action{ActivateTabRelative=1}},
	},
	
	color_scheme = "Builtin Tango Dark",


	font = wezterm.font("MesloLGS NF"), -- 13pt Line Gap S/M/L, Dotted Zero
	font_size = 13,

  	inactive_pane_hsb = {
    	saturation = 1.0,
    	brightness = 0.85,
  	},
}
```

https://user-images.githubusercontent.com/739903/150602570-2ebf7fde-0305-4c25-8fb0-425a4a60813b.mp4

**Comment by wez** [comment]
@ettoredn please file a separate issue; I don't believe what you are seeing is the same thing as you're on a different OS with a very different copy/paste architecture.

**Comment by ModProg** [comment]
> @ModProg I need to know how to reproduce the problem, otherwise I have no idea what's actually going wrong or where :-/

That makes sense, But the problem only occurs sometimes. I have an instance with that problem currently open, but no idea how I got there, which means I have no way of reproducing the error reliably.

So my question is more, if you would have any recommendation what I could do to check for the cause when I have reproduced it by accident.

At some point, wezterm seams to just stop reading the system clipboard, and will only start as soon as you copy something in wezterm. This might be related to `OSC52` but whatever it is, it does not break reliably. 

It only affects one instance (but all tabs/panes in it). When I open a new window it works there (but still broken in the old window).
