### ISSUE TITLE
Cannot `wezterm connect` to remote running wezterm AppImage

### ISSUE THREAD

**Issue by lkhphuc** [wez/wezterm#1359]
As the title, `wezterm connect remote` is not successful if using `linuxbrew`.
More specifically, I notice there is no `wezterm-mux-server` command when installed with linuxbrew. 
Installing with debian package works fine.

The error log for wezterm installed with linuxbrew is:
```
2021-11-30T15:42:44.082Z ERROR wezterm_client::client > going to run wezterm cli proxy
 2021-11-30T15:42:44.082Z INFO  wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 617 4.1 INTEL-18.2.10 is_context_loss_possible=false wezterm version: 20210814-124438-54e29167
 2021-11-30T15:42:44.244Z ERROR wezterm_client::client  > Error while decoding response pdu: decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
 2021-11-30T15:42:44.244Z ERROR wezterm_client::client  > ssh stderr: zsh:1: command not found: wezterm

 2021-11-30T15:42:44.250Z ERROR wezterm_gui             > Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU: reading PDU length: EOF while reading leb128 encoded value' while being asked for its version.  This likely means that the server is older than the client.
; terminating
 2021-11-30T15:42:44.250Z ERROR mux::connui             > while running ConnectionUI loop: recv_timeout: channel is empty and disconnected
```

**Comment by wez** [comment]
I think this is a general issue with the AppImage based installation; `wezterm-mux-server` is included in the appimage, but the PATH isn't set up so that wezterm can locate it (or event `wezterm` which is needed to spawn the cli proxy).

**Comment by wez** [comment]
I think this is fixed now with the nightly AppImage downloads; give it about 30 minutes or so to complete building and publishing, and then please try using the nightly appimage download link on https://wezfurlong.org/wezterm/install/linux.html#installing-on-linux-using-appimage to obtain `wezterm` for the remote system.

Note that you'll also need to use a nightly wezterm build for your client to verify that this is working.

**Comment by lkhphuc** [comment]
Thank for the quick fix, but unfortunately it still doesn't work.
Both wezterm client and server are now  `20211201-220624-26c727bf`, with server installed by downloading the nightly AppImage and moving it to bin folder.

Still the same error.

**Comment by wez** [comment]
I made another attempt; please give the next nightly build a try about an hour from now

**Comment by lkhphuc** [comment]
Thank to the better error log from the nightly client: `2021-12-03T14:33:32.995Z ERROR wezterm_client::client > going to run /usr/local/bin/wezterm cli proxy`, I confirm that moving/symlink the Nightly or the stable AppImage, to `/usr/local/bin/wezterm` works.

My original issue was `linuxbrew` install to a different path, and I move the AppImage to `~/.local/bin`, and even though they're both in my shell PATH, it was not picked up by `wezterm connect`. Only Debian package install it `/usr/local/bin`.

I'm happy with manually symlink my brew install to /usr/local/bin, feel free to close this issue.
