### ISSUE TITLE
Can't see emojis in terminal

### ISSUE THREAD

**Issue by erf** [wez/wezterm#1590]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220122-100747-ebaa796b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Emojis don't show up in the terminal . Like `🙂❤️` etc.

The smiley show as black space only. And the heart the same but with an additional `<fe0f>`

Do i miss some configuration here or is this feature not implemented yet?

I've added the output of `wezterm ls-fonts` at the bottom.

### To Reproduce

Copy a heart emoji from : https://emojipedia.org/red-heart/

Paste it into wezterm.

### Configuration

no config

### Expected Behavior

I expected to see the heart emoji ❤️ in the terminal 

### Anything else?

Here is the output of `wezterm ls-fonts`:

```
/ % ./Applications/WezTerm.app/Contents/MacOS/wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="JetBrains Mono", weight="ExtraLight", italic=true},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="JetBrains Mono", weight="ExtraLight"},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="JetBrains Mono", weight="Bold"},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="JetBrains Mono", weight="Bold", italic=true},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="JetBrains Mono", italic=true},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})

Title font:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="Roboto", weight="Bold"},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

**Comment by wez** [comment]
I can't reproduce this; `wezterm -n` and pasting ❤️ shows the red heart.

The `<fe0f>` sounds like your shell may be misinterpreting the emoji and printing out placeholders.
Check your shell configuration!

**Comment by wez** [comment]
`FreeType error 19 0x13: cannot render this glyph format` sounds like a freetype bug that was fixed in 2.11.1

Did you build wezterm from source?
If so: make sure that you run this after pulling so that you have the correct version of that dependency, and then build again!

```
git submodule update --init
```

**Comment by erf** [comment]
You're right! Was building from source, and had not updated the submodules. I see the emoji now but i still get the `<fe0f>`, but i guess that is a shell configuration thing you mentioned
