### ISSUE TITLE
wayland: support text-input-v3 for IME

### ISSUE THREAD

**Issue by wez** [wez/wezterm#1772]
https://docs.rs/wayland-protocols/0.29.0/wayland_protocols/unstable/text_input/v3/client/zwp_text_input_v3/index.html

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by q234rty** [comment]
Just tried wezterm 20220709-094408-e2b748a0 in GNOME wayland with ibus and 200% scaling. The main thing I noticed is that the input panel position seems to be wrong, in particular, the 200% scaling seems to be applied twice for the panel:
![图片](https://user-images.githubusercontent.com/11485439/178117615-2c69c417-3d62-4ebb-97ec-a3040b22897f.png)
Also there seems to be no preedit yet.

**Comment by wez** [comment]
both of those should hopefully be resolved now in `main`!

**Comment by q234rty** [comment]
Can confirm that these issues are resolved. However I have now noticed behavior similar to https://github.com/alacritty/alacritty/issues/6037 on both current `main` and e2b748a0. I wonder if this is a bug in one of the rust crates...

**Comment by wez** [comment]
That sounds like a pretty bad mutter bug, but it may be possible to workaround it.  I'm not at my linux box right now to try this, but I think:

* Add an `Inner::shutdown` method that iterates over https://github.com/wez/wezterm/blob/main/window/src/os/wayland/inputhandler.rs#L20 and call https://docs.rs/wayland-protocols/latest/wayland_protocols/unstable/text_input/v3/client/zwp_text_input_v3/struct.ZwpTextInputV3.html#method.disable and then https://docs.rs/wayland-protocols/latest/wayland_protocols/unstable/text_input/v3/client/zwp_text_input_v3/struct.ZwpTextInputV3.html#method.commit 
* add a method alongside https://github.com/wez/wezterm/blob/main/window/src/os/wayland/inputhandler.rs#L139 to call `shutdown`
* Add `impl Drop for WaylandConnection` over here https://github.com/wez/wezterm/blob/main/window/src/os/wayland/connection.rs#L44 and have it call ` environment.with_inner(|env| env.input_handler.shutdown());`

may help to tidy things up.

**Comment by wez** [comment]
I pushed a commit with those changes; please let me know how that works out!

**Comment by q234rty** [comment]
Sadly it still doesn't work :) Might want to use `WAYLAND_DEBUG=1` on both foot and wezterm and compare.

**Comment by q234rty** [comment]
Also apparently on both KDE wayland and sway(but not GNOME wayland for some reason) the preedit remains after the text have been commited:
![图片](https://user-images.githubusercontent.com/11485439/178133225-8c996ff3-5737-4f89-8597-cb374a845c8d.png)

**Comment by wez** [comment]
> Sadly it still doesn't work :) Might want to use `WAYLAND_DEBUG=1` on both foot and wezterm and compare.

Can you share the precise steps needed to reproduce this?

**Comment by wez** [comment]
> Also apparently on both KDE wayland and sway(but not GNOME wayland for some reason) the preedit remains after the text have been commited: ![图片](https://user-images.githubusercontent.com/11485439/178133225-8c996ff3-5737-4f89-8597-cb374a845c8d.png)

Probably fixed by 607287935fb028d836645fccac84a676ed466f08

**Comment by wengxt** [comment]
@wez I don't think your fix is correct.

I believe it's the misunderstand of how text-input-v3 works.

preedit string is double buffered, and commit with "zwp_text_input_v3@15.done".

When you simply receive done without any preedit string, it means there is no preedit string, instead of "preedit string" is not changed.

Basically the pseudo code should be:
```
on_preedit_string(preedit_string)
   pending_state.preedit_string = preedit_string

on_commit_string(commit_string)
   pending_state.commit_string = commit_string

etc..

on_done():
   apply_all_pending_state()
   reset_pending_state_to_empty()
```

commit should not be done upon commit_string,, instead, it should be applied at done.

Quote the protocol:
https://wayland.app/protocols/text-input-unstable-v3#zwp_text_input_v3:event:done
```
 The application must proceed by evaluating the changes in the following order:

1. Replace existing preedit string with the cursor. 2. Delete requested surrounding text. 3. Insert commit string with the cursor at its end. 4. Calculate surrounding text to send. 5. Insert new preedit text in cursor position. 6. Place cursor inside preedit text.
```

**Comment by wengxt** [comment]
Here's an example of an real communication and the explanation of what the application is expected to do.

[1180623.314] zwp_text_input_v3@15.preedit_string("ni hao", 0, 6)
At this point, nothing happens, because state only change at "done".
[1180624.035] zwp_text_input_v3@15.done(6)
At this point, preedit_string should be "ni hao|", all pending states are flushed and cleared.
[1182802.301] zwp_text_input_v3@15.commit_string("你好")
At this point, nothing should be changed, preedit should still be "ni hao". Again, state only applied at done().
[1182802.361] zwp_text_input_v3@15.done(6)
At this point, preedit should be updated to empty, because there is no pending preedit. And then commit "你好' .

**Comment by wez** [comment]
`main` now double-buffers the received state

**Comment by q234rty** [comment]
> Can you share the precise steps needed to reproduce this?

I'm not sure what can I add to the steps and screencast in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4776

**Comment by wez** [comment]
@q234rty hmm, well, I couldn't reproduce it.
I have this setting:
![image](https://user-images.githubusercontent.com/117777/178296373-85201165-4f3f-4152-8699-5a4156c6f81e.png)

**Comment by q234rty** [comment]
@wez Sorry I just found that this only happens when trying to switch from wezterm directly to something that uses gtk-im-module or qt-im-module. So to reproduce you need to globally set `GTK_IM_MODULE=ibus` or use any Qt app (Qt does not support text-input-v3).

**Comment by KyleUltimate** [comment]
On sway, the input box doesn't even appear. Using nighty builds.
Fcitx5 + rime. Input method rime-liur
wayland=true
![image](https://user-images.githubusercontent.com/68589851/179343261-a06a85c3-09cb-4cf7-b63e-d16406e2e84d.png)
wayland=false
![image](https://user-images.githubusercontent.com/68589851/179343285-324fdb62-4736-4676-969f-c0ac2de49bc2.png)

**Comment by wengxt** [comment]
@KyleUltimate your problem is caused by sway, has nothing to do with wezterm.

FYI: https://github.com/swaywm/sway/pull/5890

**Comment by q234rty** [comment]
Kinda offtopic but you can use sway-im in the aur which integrates https://github.com/swaywm/sway/pull/5890

**Comment by VarLad** [comment]
Thanks a lot, works like a charm for me! :)
