### ISSUE TITLE
Right control button is detected as the left control button

### ISSUE THREAD

**Issue by Event-Horizon-Labs** [wez/wezterm#2009]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Currently, when I am using Far manager, I loved Wezterm but the right control button is not been detected independently which is needed so much to move between favorite groups.

Is it possible to register that key differently from the left control one?

### Configuration

local wezterm = require 'wezterm';

return {
    disable_default_key_bindings = true,
    allow_win32_input_mode = true,
  }

**Comment by wez** [comment]
Sounds like a duplicate of https://github.com/wez/wezterm/issues/1904
Could you open an issue with the MS folks as I requested at the bottom of that other issue?

**Comment by Event-Horizon-Labs** [comment]
@wez https://github.com/microsoft/terminal/issues/13134 I hope I did it okey enough to move this forward.

**Comment by wez** [comment]
Thanks!

**Comment by wez** [comment]
I pushed a commit that fixes the main issue behind the other win32 input mode bugs reported to wezterm, where CTRL-<something> wasn't correctly reported.

Could you try that and let me know if that resolves what you're seeing with the left/right ctrl key issue?

wezterm doesn't track a distinct left/right ctrl modifier mask (because that concept isn't part of the classic terminal model), but if you're pressing just the left/right ctrl key (and not using it as a modifier) it should pass through the underlying vkey code.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Event-Horizon-Labs** [comment]
The issue is still present with this nighty version

![image](https://user-images.githubusercontent.com/1145623/170300683-4c071c83-721e-4f79-8763-8e99119622e3.png)

**Comment by wez** [comment]
Can you clarify for me what key(s) you're pressing in this situation?
Is it the right control key on its own, or are you holding the right control key together with some other key?

**Comment by wez** [comment]
Could you also turn on `debug_key_events=true` and capture the logs from the keys that you're pressing; see: https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html for more information on that.

**Comment by Event-Horizon-Labs** [comment]
[westerm_log.txt](https://github.com/wez/wezterm/files/8780498/westerm_log.txt)

Yes, for Far, we use a left control + a number for example to change the panels and right control + a number to navigate to favourites. That is why is important the distinction.

**Comment by wez** [comment]
Can you try downloading the latest nightly build? I landed a change that might help

**Comment by Event-Horizon-Labs** [comment]
![image](https://user-images.githubusercontent.com/1145623/170533771-c11accda-43cd-45a4-b6b0-47ee528868e9.png)

Works man!, that is great!

**Comment by Event-Horizon-Labs** [comment]
One more note, the control + up key is not working. I was wondering if this might be related.

**Comment by Event-Horizon-Labs** [comment]
[westerm_log2.txt](https://github.com/wez/wezterm/files/8780640/westerm_log2.txt)

**Comment by Event-Horizon-Labs** [comment]
Hi @wez do you think it is possible?

**Comment by wez** [comment]
Asking over in https://github.com/microsoft/terminal/issues/13134#issuecomment-1146811546

**Comment by Event-Horizon-Labs** [comment]
Yes!, it is working man, this is fantastic!
