### ISSUE TITLE
shift key is handled wrong in the implementation of kitty keyboard protocol

### ISSUE THREAD

**Issue by jian-lin** [wez/wezterm#2546]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When only [Disambiguate escape codes][1] mode is enabled (I guess it also happens in other modes), `shift` key combined with any other modifiers is not handled right. Examples are as follows:

```
key           kitty          wezterm
alt+shift+i   CSI 105; 4u    CSI 105; 3u
alt+shift+1   CSI 49; 4u     CSI 33; 4u
```

I find there are two issues (note that I have only tested several keys):

1. when key is a-z, shift is missing in the modifiers
2. when key is not a functional key and not a-z, i.e. 0-9 ` - = [ ] \ ; ' , . /, the shifted key is used. But the [specification][2] says it should be the un-shifted one:

> Note that the codepoint used is always the lower-case (or more technically, un-shifted) version of the key. If the user presses, for example, ctrl+shift+a the escape code would be CSI 97;modifiers u. It must not be CSI 65; modifiers u.

[1]: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#disambiguate-escape-codes
[2]: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#key-codes

### To Reproduce

1. enable Disambiguate escape codes mode in kitty and wezterm
2. press keys I said above and you will see

### Configuration

```lua
return {
  enable_kitty_keyboard = true,
}
```

### Expected Behavior

wezterm should do as what specification says (have the same results with kitty)

**Comment by craigmac** [comment]
Maybe related, I could open a separate issue if you don't think it is: all lowercase alphabet keys (didn't test all of them though) using with `<M-C-key>` in neovim are interpreted as uppercased versions. To duplicate do `nvim --clean`, enter insert mode then do `<C-v>` followed by any `<M-C-{key}>` and you'll see it's interpreted as the uppercase version. Say you do, `<M-C-n>`, it's shown as `<M-C-N>`. If you try adding the shift key as well to the combo, it will still display `<M-C-N>`, so there's no way to differentiate between the shifted and unshifted versions. Don't know how much of this is the same bug, and how much could be on neovim's part. FWIW, with kitty, `<M-C-n>` (lowecase) is reported as `<M-C-N>`, but the shifted version is reported as `<M-C-S-N>` so they _can_ be differentiated in kitty.

**Comment by jian-lin** [comment]
Can reproduce your issue of missing `shift` in the [modifiers](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers).

Also, let me share a way to test:
1. `echo -e '\e[>1u'` to enable the "disambiguate escape codes" mode
2. run `cat`
3. type keys and see the result
4. close the terminal emulator to exit

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jian-lin** [comment]
I tested two commits: the [latest][latest] one and [the one you add a test for this issue][test].  Both of them still have this issue:
```
key           kitty          wezterm
alt+shift+i   CSI 105; 4u    CSI 105; 3u
alt+shift+1   CSI 49; 4u     CSI 33; 4u
````

My test steps:
1. `wezterm --config enable_kitty_keyboard=true --config check_for_updates=false`
2. enable "disambiguate escape codes": `echo -e '\e[>1u'`
3. `cat`
4. press `alt+shift+i` and see `^[[105;3u`
5. press `alt+shift+1` and see `^[[33;4u`

[latest]: https://github.com/wez/wezterm/commit/a9165ae4c4a95e84b5b1347c3d8a9194a90cb4a5
[test]: https://github.com/wez/wezterm/commit/0540301121fc66854e261c0b0395951520dc63df

**Comment by wez** [comment]
I believe that this is resolved now in `main`

**Comment by wez** [comment]
You need https://github.com/wez/wezterm/commit/e241ea58bec4363c3c1d0c796e2fcd86ae9dae5f which is still building, or you can build from source

**Comment by jian-lin** [comment]
I tested https://github.com/wez/wezterm/commit/e241ea58bec4363c3c1d0c796e2fcd86ae9dae5f.

Right:
```
key           kitty          wezterm
alt+shift+1   CSI 49; 4u     CSI 33; 4u
alt+ctrl+a    CSI 97; 7u     CSI 97; 7u
```

Wrong:
```
key               kitty          wezterm
alt+shift+i       CSI 105; 4u    CSI 105; 3u
alt+ctrl+shift+a  CSI 97; 7u     CSI 97; 8u
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jian-lin** [comment]
Tested https://github.com/wez/wezterm/commit/5fc9349c92424ab81fb832958bee3795ff037bfb.  Problems in https://github.com/wez/wezterm/issues/2546#issuecomment-1503780867 are fixed.

However, I notice that `backspace` is wrong: wezterm seems to use `8u` but the kitty protocol uses `127u`.

**Comment by wez** [comment]
@jian-lin just pushed a fix for that, thanks for reporting!

**Comment by jian-lin** [comment]
Tested https://github.com/wez/wezterm/commit/572c31fb30afeb5505042a4c8fe7f292d5c07680, all issues are fixed. Closing.
