### ISSUE TITLE
can not control cursor color in nvim using guicursor option

### ISSUE THREAD

**Issue by jdhao** [wez/wezterm#2635]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221015-164502-7b904f05

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

setting the `guicursor` option for nvim can not change the cursor color when opening nvim inside wezterm.

### To Reproduce

Content of `test.vim`:

```
set termguicolors
hi Cursor guifg=black guibg=red
set guicursor=n-v-c:block-Cursor/lCursor
```

Run nvim inside wezterm using following command:

```
nvim --clean -u test.vim test.vim
```

### Configuration

no config

### Expected Behavior

The cursor should be changed to red in normal mode, but instead it is not changed to red.

If I use the above config in kitty, the cursor is changed to red when opening nvim inside kitty.

**Comment by wez** [comment]
I think you may want to install and enable the wezterm terminfo for this to work.
https://wezfurlong.org/wezterm/faq.html#how-do-i-enable-undercurl-curly-underlines has information about this

**Comment by jdhao** [comment]
I have already done this (for the curly underline stuff). This does not work.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/16662357/196043786-ceba36f3-c8f1-4729-a936-6583745de9cb.png">

**Comment by wez** [comment]
In https://github.com/wez/wezterm/issues/1625 it sounded like you already had this working?

Per my comments in https://github.com/wez/wezterm/issues/1073, I think this class of issue is more a question for the neovim folks: the terminal supports this functionality, but it's not clear what neovim uses to decide to use it.  If you can go and find out, we can figure out what to do next.

**Comment by jdhao** [comment]
yeah, it once works, now wezterm and neovim both have a lot of updates, it stops working. If it is an neovim issue, I suppose kitty would also break? I do not know the internals, so do not know how to proceed.

**Comment by wez** [comment]
Using `printf "\x1b]12;#ff00ff\x1b\\"` in the shell does change the cursor color, but I think there is a cache invalidation issue that makes it not immediately appear.
If you use ctrl-+ or ctrl-- to change the font size, does the color get corrected in nvim?

**Comment by jdhao** [comment]
No, using `ctrl--` and `ctrl-+` change the font size, but the color is not changed.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/16662357/196097134-6257a401-8e73-4e0a-8553-3d74337e1982.png">

**Comment by zim0369** [comment]
I'm facing the exact same problem. In neovim, wezterm's cursor overrides neovim's colorscheme specific cursor.

Another problem is that the cursor doesn't have a foreground so in neovim I can't see the text under my cursor.

**Comment by jdhao** [comment]
Related issue opened: https://github.com/neovim/neovim/issues/20706.

The neovim dev said this is a problem of wezterm terminfo file. I am not sure which is right since I do not know the internal source code.

**Comment by wez** [comment]
@jdhao that other issue is for the title string, which is now resolved by updating the terminfo file in `main`, however, this issue is about the guicursor, which wasn't discussed in https://github.com/neovim/neovim/issues/20706

**Comment by jdhao** [comment]
okay, assume i use `wezterm` as `TERM`,  What should I do to make guicursor work?

**Comment by wez** [comment]
I think we need to ask the nvim folks about this explicitly!

**Comment by jdhao** [comment]
okay, if this issue is not related to `title`, I will open a separate issue in neovim repo.

**Comment by wez** [comment]
I fixed a cache invalidation issue with the cursor color in `main` just now; it may affect this issue, but I'm not sure.
Could you try a nightly build in about an hour (once it builds out), or build from source and try that?

**Comment by jdhao** [comment]
I tried latest version (commit `36f215c03e6fef26e841df20e880c695de0358a2`), the cursor color still does not work.

**Comment by ratheesh** [comment]
@jdhao , I just tried with latest commit(`a7332ba9b429f9676723eb88cffb2068f5a95c9b`) from Neovim and cursor color settings through `guicursor` works fine.

**Comment by janislaus** [comment]
I'm still having this issue. Can reproduce it with the stable and nightly build of wezterm on ubuntu 22.04 and windows 10. The guicursor color is set properly in all other terminal emulators I've tried (Kitty, Gnome and Alacritty).
Are there any updates on this?

**Comment by bugabinga** [comment]
I can reproduce this issue, but **only** when `cursor_thickness = '1cell'` is set in my `wezterm.lua`.

The symptom seems to be that with above setting the cursor is always* a 1cell block of in wezterm configured color, regardless of the `guicursor` option or `Cursors` highlight in neovim.

*
: not really always. It is complicated. Foreground color set in neovim seems to always be ignored by wezterm. Background color can be changed in some mode (normal, visual) but not in others (insert).

It is possible, that we have a beautiful interplay of 2 bugs in wezterm and neovim, but I think it is safe to assume we have an issue in wezterm in regards to the `cursor_thickness = '1cell'`-setting.

**Comment by david-haerer** [comment]
I also experience this issue. Here are some relevant infos

* NeoVim version `v0.10.0-dev-1956+gec7453804`.
* Wezterm version `20230712-072601-f4abf8fd`.
* Wezterm color scheme `Ayu Dark (Gogh)`.

I'd like to get it fixed, so I'm thankful for any hint for debugging.

**Comment by wez** [comment]
I fixed a different invalidation issue just now that may relate to this issue.
That should be available in nightly builds within about an hour; please give it a try and let me know if that was really it this time!

**Comment by kuznetsss** [comment]
Hi @wez, thanks for trying to fix it!

I downloaded the artifact from https://github.com/wez/wezterm/actions/runs/7748751221, unpacked and run `WezTerm-macos-20240201-155814-aa94a983/WezTerm.app/Contents/MacOS/wezterm`.

Unfortunately the cursor stays the same color in neovim 0.9.5. I have terminfo installed and I tryied to start nvim with `TERM=wezterm`.

The interesting thing is that for both the latest release and this nightly build cursor does change color in the command window of [noice.nvim](https://github.com/folke/noice.nvim). But this happens only there, maybe that window has a different cursor color implementation.
![Screenshot 2024-02-02 at 13 16 03](https://github.com/wez/wezterm/assets/15742918/62392ac6-6be2-4dd0-a2ea-235fc226eaf6)

**Comment by wez** [comment]
Looking at this again: `printf "\x1b]12;#8000ff\x1b\\"` works to immediately set the cursor color, so the fundamental capability works.
If nvim cannot set it, then we need some to ask the nvim folks how it decides whether the cursor color can be changed, then we can figure out how to close that gap.
I do not use nvim and do not have time to do this.
I asked previously in this for someone to reach out to the neovim folks explicitly about this, but I don't know if that happened.

**Comment by kuznetsss** [comment]
I think the issue is related only to inversed cursor color. And I just realised it happens not only in neovim.

Zsh syntax highlighting in Alacritty:
![Screenshot 2024-02-03 at 10 55 14](https://github.com/wez/wezterm/assets/15742918/f73538ef-647c-47b6-8466-6fecb9bc53af)

Zsh syntax highlighting in WezTerm:
![Screenshot 2024-02-03 at 10 55 30](https://github.com/wez/wezterm/assets/15742918/d7e67ed6-260e-4425-b27c-c8383c122529)

**Comment by david-haerer** [comment]
Thanks a lot for the insight! For me that solves the issue. 🎉

**Comment by kuznetsss** [comment]
@wez, could you please review this issue and the related one in Neovim?
I think the problem was only in different defaults and setting `force_reverse_video_cursor = true` solves the probem.
If you agree I assume we could close this issue.

**Comment by wez** [comment]
I looked at it the other day; it seems like the color isn't being changed at all in nvim, so `guicursor` is a red herring and that the problem is just that the expectation was that the cursor be in reverse video mode, which is not the default mode in wezterm.

I'm happy to close this.
