### ISSUE TITLE
flatpak release: Unable to set cursor to left_ptr: cursor not found

### ISSUE THREAD

**Issue by sdroege** [wez/wezterm#2687]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

gnome-shell

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Running the current release from flathub as of today gives lots of warnings as follows

```
17:08:48.768  ERROR  window::os::wayland::frame > Unable to set cursor to bottom_side: cursor not found
17:08:48.772  ERROR  window::os::wayland::frame > Unable to set cursor to left_ptr: cursor not found
17:08:48.772  ERROR  window::os::wayland::frame > Unable to set cursor to left_ptr: cursor not found
17:08:48.772  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
17:08:48.773  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
17:08:48.774  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
17:08:48.775  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
17:08:48.776  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
```

The cursors are also indeed not changing correctly, e.g. when going to the edges of the window for resizing.

The same works correctly when building the current version locally from git.

### To Reproduce

Just run it via `flatpak run org.wezfurlong.wezterm`

### Configuration

no config

### Expected Behavior

Not hundreds of lines of errors and cursors are changing correctly.

**Comment by wez** [comment]
To troubleshoot, see: https://wezfurlong.org/wezterm/faq.html#i-use-x11-or-wayland-and-my-mouse-cursor-theme-doesnt-seem-to-work

I think you probably want to try running something like this to see more diagnostics:

```
flatpak run --env=WEZTERM_LOG=window::os::x11::cursor=trace,window::os::wayland::pointer=trace,info org.wezfurlong.wezterm
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by sdroege** [comment]
> If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

The "problem" here is that it works fine with builds from source and will probably also work fine with things like .appimage because it doesn't provide any sandboxing :)

I'll check again the next flatpak release and re-open if the problem persists. Thanks for looking into this!

**Comment by sdroege** [comment]
The same still happens with the latest flatpak release (wezterm 20221119-145034-49b9839f)

**Comment by wez** [comment]
What does:

```
flatpak run --env=WEZTERM_LOG=window::os::x11::cursor=trace,window::os::wayland::pointer=trace,info org.wezfurlong.wezterm
```

output?

**Comment by sdroege** [comment]
Same as before

```console
$ flatpak run --env=WEZTERM_LOG=window::os::x11::cursor=trace,window::os::wayland::pointer=trace,info org.wezfurlong.wezterm
19:38:16.897  ERROR  window::os::wayland::frame > Unable to set cursor to left_ptr: cursor not found
19:38:16.955  ERROR  window::os::wayland::frame > Unable to set cursor to left_ptr: cursor not found
19:38:16.957  ERROR  window::os::wayland::pointer > Unable to set cursor to arrow: cursor not found
19:38:16.964  ERROR  window::os::wayland::frame   > Unable to set cursor to left_ptr: cursor not found
19:38:17.467  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:38:17.477  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:38:17.480  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:38:17.482  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:38:17.484  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:38:17.487  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
[...]

**Comment by bldur** [comment]
Just followed build from git main branch and seeing the same, on gentoo with sway.

**Comment by sdroege** [comment]
When switching the host from Debian to Fedora, the problem inside the flatpak container goes away. So there must be something about how the container inherits cursor themes that is the problem here.

**Comment by bldur** [comment]
> When switching the host from Debian to Fedora, the problem inside the flatpak container goes away. So there must be something about how the container inherits cursor themes that is the problem here.

After seeing this, built from source, on gentoo.
Flatpak doesn't look to come bundled, and there are no in-built themes for mouse pointers/cursors.
The fix look to have been, "more effort towards finding one".

Someone is packaging it for guix, so guix binary install or guix built container will also be possible.

**Comment by devmatteini** [comment]
I have the same problem on Ubuntu 22.04 with Gnome and Wayland.
I installed the `.deb` version (`wezterm-20221119-145034-49b9839f.Ubuntu22.04.deb`)

For me, it's happening when resign a pane:
```
23:33:40.798 ERROR window::os::wayland::pointer > Unable to set cursor to ew-resize: cursor not found
23:33:40.877 ERROR window::os::wayland::pointer > Unable to set cursor to ew-resize: cursor not found
23:33:41.028 ERROR window::os::wayland::pointer > Unable to set cursor to ew-resize: cursor not found
23:33:41.140 ERROR window::os::wayland::pointer > Unable to set cursor to ew-resize: cursor not found
```

**Comment by bldur** [comment]
> I am still getting these errors using the flatpak version (wezterm 20230712-072601-f4abf8fd) on Pop!_OS 22.04.
> 
> Starting it with `XCURSOR_PATH=/usr/share/icons XCURSOR_THEME=Adwaita flatpak run org.wezfurlong.wezterm` works around the issue, but it's not working out of the box. What's worse, when you launch wezterm it via the system launcher, this problem prevents resizing the window using mouse / drag window corners.

And there are so many ways of dealing with X related themes, back in the day when you had to walk in two feet of snow over a mountain to obtain something that looked better than FVWM. You'd be certain there was only the environment variables and simple text files to deal with. Now you still have this, and and extended filesystem hierarchy standard and priorities.

Is it broken without working out of the box for all obscure distros and OS flavours? Documenting it is probably sufficient?

**Comment by mhantsch** [comment]
> > I am still getting these errors using the flatpak version (wezterm 20230712-072601-f4abf8fd) on Pop!_OS 22.04.
> Is it broken without working out of the box for all obscure distros and OS flavours? Documenting it is probably sufficient?

My point is that a flatpak should work independent of the choice of distro. @devmatteini had the same issue on Ubuntu; that's not even an obscure distro.

**Comment by bldur** [comment]
> > > I am still getting these errors using the flatpak version (wezterm 20230712-072601-f4abf8fd) on Pop!_OS 22.04.
> > > Is it broken without working out of the box for all obscure distros and OS flavours? Documenting it is probably sufficient?
> 
> My point is that a flatpak should work independent of the choice of distro. @devmatteini had the same issue on Ubuntu; that's not even an obscure distro.

It does work, but is excessive regarding not finding a local home or system default mouse pointer theme.
There is reason to suspect there are lots of performance related things like it.

My point is, if you are going for configurable eye kinda terminal with ligature fonts support, you may care about being pointed in a direction to fix it. And applications may inherent wezterm overrides.

**Comment by bldur** [comment]
> @bldur Thanks for all your pointers, they are useful. I can do all of that, yes. I should, however, not have to jump through those hoops.
<snip>
> I think WezTerm is an extremely capable terminal; however it's integration in standard setups has room for improvement.
> 
> This will be my last comment on this topic.

I get the frustration, but terminals have a long history of problems and is not easy.
My issue is mostly about performance, can get laggy with ligatures in large windows.
Quite a lot of features, and there is no going back to urxvt or suckless with heavy reliance on tmux.

Adding fonts here wouldn't be major, and many new users will try a config from github.
Here is my config, and some work required to find the fonts.

`local wezterm = require 'wezterm';
local act = wezterm.action

local mux = wezterm.mux

-- this is called by the mux server when it starts up.
-- It makes a window split top/bottom
--wezterm.on('mux-startup', function()
--  local tab, pane, window = mux.spawn_window {}
--  pane:split { direction = 'Top' }
--  pane:split { direction = 'Right' }
--end)


return {
--    default_prog = {"/usr/bin/zsh", "-l"},
--    color_scheme = "Tomorrow Night Blue",
--    color_scheme = "Nord",
    color_scheme = "Zenburn",
    color_scheme_dirs = { os.getenv("HOME") .. "/.config.wezterm/colors/" },
    font_size = 8.0,
    underline_thickness = "75%",
    underline_position = "75%",
    strikethrough_position ="130%",
    dpi = 96.0,
    font_dirs = { os.getenv("HOME") .. "/.local/share/fonts/" },
    font = wezterm.font_with_fallback {
      { family = 'FiraCode', weight = 'Regular',
        harfbuzz_features = { 'cv13', 'cv18', 'cv31', 'ss03' },
      },
      'FiraCode',
      'VictorMono',
      'Noto Color Emoji',
      'Symbols Nerd Font Mono',
    },
    harfbuzz_features = { 'kern', 'liga', 'clig', 'calt' },
    font_rules = {
    -- Select a fancy italic font for italic text
      {
        italic = true,
        intensity = "Normal",
        font = wezterm.font { family = 'VictorMono',
          weight = 'Medium', style = 'Italic' },
      },
      -- Similarly, a fancy bold+italic font
      {
        intensity = "Bold",
        italic = true,
        font = wezterm.font { family = 'VictorMono',
          weight = "Bold", style = 'Italic' },
      },
    -- Make regular bold text a different color to make it stand out even more
      {
        intensity = 'Bold',
        font = wezterm.font { family = 'FiraCode',
          weight = 'DemiBold', style = 'Normal',
          harfbuzz_features = { 'ss03', 'cv13', 'cv18', 'cv31' },
        },
      },
    -- For half-intensity text, use a lighter weight font
      {
        italic = true,
        intensity = 'Half',
        font = wezterm.font { family = 'VictorMono',
          weight = 'Light', style = 'Italic' },
      },
      {
        intensity = 'Half',
        italic = false,
        font = wezterm.font { family = 'VictorMono',
          weight = "Light", harfbuzz_features = { 'ss04' }},
      },
    },
    font_shaper = "Harfbuzz",
    -- https://github.com/rubjo/victor-mono
    -- https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets
    -- ss04 is for victor as cv13 is 0 for fira that change $ with ss04
    -- ss05 @, cv18 %, ss10 FfT lig,
    freetype_interpreter_version = 40,
    freetype_render_target = "HorizontalLcd",
--    freetype_load_flags = 'MONOCHROME|NO_AUTOHINT',
--    freetype_load_target = "Light",
--    freetype_render_target = "Normal",

----------------------

--[[
    ssh_domains = {
    {
      -- This name identifies the domain
      name = "Devup",
      -- The address to connect to
      remote_address = "localhost",
      -- The username to use on the remote host
      username = "luser",
    },
  },
--]]
--[[
  unix_domains = {
    {
      name = 'unix',
    },
  },
--]]
  -- This causes `wezterm` to act as though it was started as
  -- `wezterm connect unix` by default, connecting to the unix
  -- domain on startup.
  -- If you prefer to connect manually, leave out this line.
  -- default_gui_startup_args = { 'connect', 'unix' },
-----------------------------------
launch_menu = {
    {
      args = { 'top' },
    },
    {
      -- Optional label to show in the launcher. If omitted, a label
      -- is derived from the `args`
      label = 'aktiv.prokrastinering',
      -- The argument array to spawn.  If omitted the default program
      -- will be used as described in the documentation above
      args = { 'ssh', '-i ~/.ssh/id_ecdsa', 'bldr@aktiv.prokrastinering.net' },

      -- You can specify an alternative current working directory;
      -- if you don't specify one then a default based on the OSC 7
      -- escape sequence will be used (see the Shell Integration
      -- docs), falling back to the home directory.
      -- cwd = "/some/path"

      -- You can override environment variables just for this command
      -- by setting this here.  It has the same semantics as the main
      -- set_environment_variables configuration option described above
      -- set_environment_variables = { FOO = "bar" },
    },
  },
-----------------------------------

----------------------------------
    enable_wayland = true,
    hide_tab_bar_if_only_one_tab = false,
    use_fancy_tab_bar = false,
--    selection_word_boundary = " \t\n{}[]()\"'`,;:│=&!%",
    window_padding = {
                left = 0,
                right = 0,
                top = 0,
                bottom = 0,
              },
    window_background_opacity = 0.9,
    animation_fps = 1,
--    front_end = "Software",
    pane_focus_follows_mouse = true,
    disable_default_key_bindings = true,
    leader = { key = "Space", mods = "CTRL|SHIFT" },
    keys = {
      --- tmux ---
        { key = "k", mods = "ALT", action = act({ SpawnTab = "CurrentPaneDomain" }) },
        { key = "j", mods = "ALT", action = act({ CloseCurrentTab = { confirm = true } }) },
        { key = "h", mods = "ALT", action = act({ ActivateTabRelative = -1 }) },
        { key = "l", mods = "ALT", action = act({ ActivateTabRelative = 1 }) },
        { key = "h", mods = "ALT|CTRL", action = act({ MoveTabRelative = -1 }) },
        { key = "l", mods = "ALT|CTRL", action = act({ MoveTabRelative = 1 }) },
        {
                key = "k",
                mods = "ALT|CTRL",
                action = act.Multiple({ act.CopyMode("ClearSelectionMode"), act.ActivateCopyMode, act.ClearSelection }),
        },
        { key = "j", mods = "ALT|CTRL", action = act({ PasteFrom = "PrimarySelection" }) },
--        { key = "1", mods = "ALT", action = act({ ActivateTab = 0 }) },
--        { key = "2", mods = "ALT", action = act({ ActivateTab = 1 }) },
--        { key = "3", mods = "ALT", action = act({ ActivateTab = 2 }) },
--        { key = "4", mods = "ALT", action = act({ ActivateTab = 3 }) },
--        { key = "5", mods = "ALT", action = act({ ActivateTab = 4 }) },
--        { key = "6", mods = "ALT", action = act({ ActivateTab = 5 }) },
--        { key = "7", mods = "ALT", action = act({ ActivateTab = 6 }) },
--        { key = "8", mods = "ALT", action = act({ ActivateTab = 7 }) },
--        { key = "9", mods = "ALT", action = act({ ActivateTab = 8 }) },
        { key = "-", mods = "ALT", action = act({ SplitVertical = { domain = "CurrentPaneDomain" } }) },
        { key = "\\", mods = "ALT", action = act({ SplitHorizontal = { domain = "CurrentPaneDomain" } }) },
        { key = "h", mods = "ALT|SHIFT", action = act({ ActivatePaneDirection = "Left" }) },
        { key = "l", mods = "ALT|SHIFT", action = act({ ActivatePaneDirection = "Right" }) },
        { key = "k", mods = "ALT|SHIFT", action = act({ ActivatePaneDirection = "Up" }) },
        { key = "j", mods = "ALT|SHIFT", action = act({ ActivatePaneDirection = "Down" }) },
        { key = "h", mods = "ALT|SHIFT|CTRL", action = act({ AdjustPaneSize = { "Left", 1 } }) },
        { key = "l", mods = "ALT|SHIFT|CTRL", action = act({ AdjustPaneSize = { "Right", 1 } }) },
        { key = "k", mods = "ALT|SHIFT|CTRL", action = act({ AdjustPaneSize = { "Up", 1 } }) },
        { key = "j", mods = "ALT|SHIFT|CTRL", action = act({ AdjustPaneSize = { "Down", 1 } }) },
        { key = "Enter", mods = "ALT", action = "QuickSelect" },
        { key = "f", mods = "CTRL|SHIFT", action = act.Search("CurrentSelectionOrEmptyString") },
        ---- Defaults Bindings ----
        { key = "c", mods = "CTRL|SHIFT", action = act({ CopyTo = "Clipboard" }) },
        { key = "v", mods = "CTRL|SHIFT", action = act({ PasteFrom = "Clipboard" }) },
        { key = "Insert", mods = "SHIFT", action = act({ PasteFrom = "PrimarySelection" }) },
        { key = "=", mods = "CTRL", action = "ResetFontSize" },
        { key = "+", mods = "CTRL", action = "IncreaseFontSize" },
        { key = "-", mods = "CTRL", action = "DecreaseFontSize" },
        { key = "PageUp", mods = "ALT", action = act({ ScrollByPage = -1 }) },
        { key = "PageDown", mods = "ALT", action = act({ ScrollByPage = 1 }) },
        { key = "z", mods = "ALT", action = "ReloadConfiguration" },
        { key = "z", mods = "ALT|SHIFT", action = act({ EmitEvent = "toggle-tmux-keybinds" }) },
        { key = "e", mods = "ALT", action = act({ EmitEvent = "trigger-nvim-with-scrollback" }) },
        { key = "q", mods = "ALT", action = act({ CloseCurrentPane = { confirm = true } }) },
        { key = "x", mods = "ALT", action = act({ CloseCurrentPane = { confirm = true } }) },
--        { key = "u", mods = "CTRL|SHIFT", action = "CharSelect" },
        {
          key = 'u',
          mods = 'SHIFT|CTRL',
          action = act.CharSelect {
          copy_on_select = true,
          copy_to = 'ClipboardAndPrimarySelection',
          },
        },
        {
                key = "r",
                mods = "ALT",
                action = act({
                        ActivateKeyTable = {
                                name = "resize_pane",
                                one_shot = false,
                                timeout_milliseconds = 3000,
                                replace_current = false,
                        },
                }),
        },
        { key = "s", mods = "ALT", action = act.PaneSelect({
                alphabet = "1234567890",
        }) },
        {
                key = "b",
                mods = "ALT",
                action = act.RotatePanes("CounterClockwise"),
        },
        { key = "f", mods = "ALT", action = act.RotatePanes("Clockwise") },

    },

--------------------------------------------------------------------

    colors = {
        tab_bar = {

            -- The color of the strip that goes along the top of the window
            background = "#262626",

            -- The active tab is the one that has focus in the window
            active_tab = {
                -- The color of the background area for the tab
                bg_color = "#404040",
                -- The color of the text for the tab
                fg_color = "#c0c0c0",

                -- Specify whether you want "Half", "Normal" or "Bold" intensity for the
                -- label shown for this tab.
                -- The default is "Normal"
                intensity = "Bold",

                -- Specify whether you want "None", "Single" or "Double" underline for
                -- label shown for this tab.
                -- The default is "None"
                underline = "None",

                -- Specify whether you want the text to be italic (true) or not (false)
                -- for this tab.  The default is false.
                italic = false,

                -- Specify whether you want the text to be rendered with strikethrough (true)
                -- or not for this tab.  The default is false.
                strikethrough = false,
            },

            -- Inactive tabs are the tabs that do not have focus
            inactive_tab = {
                bg_color = "#202020",
                fg_color = "#808080",

                -- The same options that were listed under the `active_tab` section above
                -- can also be used for `inactive_tab`.
            },

            -- You can configure some alternate styling when the mouse pointer
            -- moves over inactive tabs
            inactive_tab_hover = {
                bg_color = "#363636",
                fg_color = "#909090",
                italic = false,

                -- The same options that were listed under the `active_tab` section above
                -- can also be used for `inactive_tab_hover`.
            }
        }
    }
}
`

**Comment by bldur** [comment]
``

> @bldur Thanks for all your pointers, they are useful. I can do all of that, yes. I should, however, not have to jump through those hoops.
> 
<snip>
> 
> I think WezTerm is an extremely capable terminal; however it's integration in standard setups has room for improvement.
> 
> This will be my last comment on this topic.

Well, it is not xterm, and especially not unicode-rxvt or suckless with reliance on tmux.

Here is my config that come with performance issues with excessive ligatures in the text.
And the fact that i can CTRL|SHIFT U, and get a popup menu to select emojis...
It's a terminal on the edge! 😀 copy pasted from wezterm prompt.

https://github.com/bldur/configs/blob/main/wezterm/wezterm.lua
