### ISSUE TITLE
CTRL modifiers don't work on non-latin layouts

### ISSUE THREAD

**Issue by Felixoid** [wez/wezterm#2845]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE plasma, but it's reproducible on both X11 and Wayland

### WezTerm version

20221206-093635-92e851d6

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

As described in #678, the CTRL modifiers don't work in the terminal when the RU keyboard layout is active

### To Reproduce

Open `wezterm`, change layout to non-latin, try `^c` or `^s`

### Configuration

no additional configuration

### Expected Behavior

ctrl-shortcuts should work by `Phisical(S)` and not `Char('ы')`

### Logs

```
> wezterm --config debug_key_events=true
15:34:08.937  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
15:34:08.937  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
15:34:08.937  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=NONE
15:34:09.348  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(S), modifiers: CTRL, phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
15:34:09.348  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('ы'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(S), modifiers: CTRL, phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
15:34:09.348  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('ы') mods=CTRL
15:34:09.349  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "ы", Char('ы') CTRL
15:34:09.443  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('ы'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(S), modifiers: CTRL, phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
15:34:09.443  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('ы') mods=CTRL
15:34:09.951  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
15:34:09.951  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL
```

**Comment by Felixoid** [comment]
Dear @wez, is there anything I could add here to clarify the problematic code? I've tried to dig into the code, but I have zero experience with rust, unfortunately

**Comment by Felixoid** [comment]
Dear @wez, happy New Year!

Have you had a chance to take a look at the issue?

**Comment by wez** [comment]
Hi! Sorry, I haven't been able to get to this yet.
Have you tried setting `use_ime = false`?

The behavior you're describing sounds similar to AltGr processing on Windows, but with the Ctrl key instead of the Alt key in the RU layout.

Perhaps there is a need for something like `send_composed_key_when_left_alt_is_pressed`
as described in https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key but for  the CTRL key?

**Comment by Felixoid** [comment]
I've tried the config, it behaves the same way:

```
$ wezterm --config debug_key_events=true --config use_ime=true
11:27:59.277  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:27:59.278  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:27:59.278  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=NONE
11:28:00.198  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:00.198  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('c'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:28:00.198  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('c') mods=CTRL
11:28:00.198  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{3}", Char('c') CTRL
11:28:00.282  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('c'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:28:00.282  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('c') mods=CTRL
11:28:00.732  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:28:00.732  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL
11:28:01.436  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:02.363  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:02.363  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:28:02.363  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Control mods=NONE
11:28:02.729  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:02.729  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('с'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:28:02.729  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('с') mods=CTRL
11:28:02.729  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "с", Char('с') CTRL
11:28:02.807  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('с'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:28:02.807  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('с') mods=CTRL
11:28:03.668  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:28:03.668  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL
11:28:08.520  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:09.016  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:09.016  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:28:09.016  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Control mods=NONE
11:28:09.536  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:09.536  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('c'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:28:09.536  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('c') mods=CTRL
11:28:09.536  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{3}", Char('c') CTRL
11:28:09.583  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('c'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:28:09.583  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('c') mods=CTRL
11:28:09.739  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(D), modifiers: CTRL, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:28:09.739  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('d'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(D), modifiers: CTRL, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:28:09.739  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('d') mods=CTRL
11:28:09.739  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{4}", Char('d') CTRL
$ wezterm -V                                         
wezterm 20221119-145034-49b9839f
```

**Comment by gagbo** [comment]
I have the same issue on MacOS (I'm using a WIP alternative french layout called Optimot), and I need to have `use_ime = false` to get the `^{key}` combinations working. I don't know if having `use_ime = false` implies regressions though, I just found out this issue.

```console
# Installed with brew
$ wezterm --version
wezterm 20221119-145034-49b9839f
```

**Comment by wez** [comment]
@gagbo this specific issue is tracking something that applies only to X11/Wayland. I think you're experiencing this macOS issue:
* https://github.com/wez/wezterm/issues/2771

**Comment by Ernest0x** [comment]
My experience with the Greek layout keyboard in KDE is that WezTerm's shortcuts with Ctrl + Shift + Alt modifiers are working if the left-side modifier keys are pressed (LeftCtrl + LeftShift + LeftAlt) and not working if the right-side modifier keys are pressed (RightCtrl + RightShift + RightAlt). This happens even with the system-level shortcut for keyboard layout change disabled (so, it could be unrelated to the issue #3010 I had opened before).

**Comment by Felixoid** [comment]
Hello, another kind reminder about the issue. Just checked, it's the same behavior on version `20230408-112425-69ae8472`

**Comment by wez** [comment]
@Felixoid I just pushed a commit to `main` that seems to help here. It works similarly to the way that kitty handled its equivalent issue:
* https://github.com/kovidgoyal/kitty/issues/606

**Comment by Felixoid** [comment]
Yay, it looks solved to me!

```
> wezterm --config debug_key_events=true --config use_ime=false
xkbcommon: ERROR: /home/felixoid/.XCompose:4:13: unrecognized keysym "_" on left-hand side
20:01:34.432  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
20:01:34.432  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Enter mods=NONE
20:01:36.197  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(D), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
20:01:36.197  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('в'), modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(D), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
20:01:36.197  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('в') mods=NONE
20:01:36.197  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "в", Char('в') NONE
20:01:36.311  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('в'), modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(D), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
20:01:36.311  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('в') mods=NONE
20:01:36.510  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(S), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
20:01:36.510  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('ы'), modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(S), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
20:01:36.510  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('ы') mods=NONE
20:01:36.510  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "ы", Char('ы') NONE
20:01:36.612  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('ы'), modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(S), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
20:01:36.612  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('ы') mods=NONE
20:01:37.471  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
20:01:37.471  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftControl, modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
20:01:37.471  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=LeftControl mods=NONE
20:01:37.877  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(C), modifiers: CTRL, leds: NUM_LOCK, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
20:01:37.877  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('c'), modifiers: CTRL, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, leds: NUM_LOCK, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
20:01:37.877  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('c') mods=CTRL
20:01:37.877  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{3}", Char('c') CTRL
20:01:37.943  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('с'), modifiers: CTRL, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL, leds: NUM_LOCK, phys_code: Some(C), raw_code: 54, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
20:01:37.943  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('с') mods=CTRL
20:01:38.931  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(D), modifiers: CTRL, leds: NUM_LOCK, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
20:01:38.931  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('d'), modifiers: CTRL, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(D), modifiers: CTRL, leds: NUM_LOCK, phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
20:01:38.931  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('d') mods=CTRL
20:01:38.931  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{4}", Char('d') CTRL
```

**Comment by Ernest0x** [comment]
@wez the commit didn't solve the case I had mentioned above about (LeftCtrl + LeftShift + LeftAlt) working but (RightCtrl + RightShift + RightAlt) not working in greek layout. This happens because in greek layout there is a distinction between Alt and AltGr, and the LeftAlt is registered as Alt while the RightAlt is registered as AltGr. So, for example, in greek layout, the shortcut for horizontal split is not working when pressing (RightCtrl + RightShift + RightAlt + %), whereas it is working when pressing (RightCtrl + RightShift + LeftAlt + %).

I am not sure if your recent patch was expected to also catch this case with Alt vs AltGr or if it was only to help with the shortcuts such as (Ctrl + d) in different layouts. In any case, I confirm myself too that, with this patch, (Ctrl +d) now works with the greek layout. So, thank you for this improvement  at least!

**Comment by wez** [comment]
@Ernest0x that sounds like a separate issue to me. On macOS we have some options that control when we route keys via the IME/composition layer: https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key it sounds like perhaps this same concept should be introduced to X11/Wayland.  Please open a separate issue to track that!

**Comment by Ernest0x** [comment]
@wez thanks, I have opened #3578 to track this.

**Comment by olaf-rogalsky** [comment]
Now, after the recent commit, pressing Ctrl-Z gives the ascii character ^Y and Ctrl-Y gives ^Z. This is because in the german keyboard layout (among other differences) the keys for Y and Z are swapped.

**ctrl-shortcuts should work by Phisical(S) and not Char('ы')**
I tend to disagree and think, that Ctrl-characters _should_ work by Char(.), so that Ctrl keypresses reflect what a user visually sees on the keycaps of his keyboard and not what he would see, if he had an US keyboard. All other terminal emulators which I know of work on the Char(.). E.g. with Xterm I even can produce the escape character by pressing Ctrl-AltGr-8, where AltGr-8 alone produces the character "[".

**Comment by wez** [comment]
@olaf-rogalsky see https://github.com/wez/wezterm/issues/3610

**Comment by Felixoid** [comment]
should we close the issue as solved? I think so, unless there's some hidden part
