### ISSUE TITLE
laggy tab repainting when making heavy use of foreground process information

### ISSUE THREAD

**Issue by saurabhchardereal** [wez/wezterm#2991]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

BSPWM + picom as compositor

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

As discussed [here](https://github.com/wez/wezterm/discussions/628#discussioncomment-4745591), after customizing tabs and subsequently opening them multiple times is causing quite noticeable lag.

**System Info:**
Arch Linux + ZSH (5.9) (with [powerlevel10k](https://github.com/romkatv/powerlevel10k))

Also here's a screen recording:

https://user-images.githubusercontent.com/51372520/213878562-e33fec07-82cc-43b1-85b2-7cbf86ec5b6a.mp4

### To Reproduce

Can be reproduced using the minimal config given below.

### Configuration

```lua
local wezterm = require("wezterm")

local function get_process(tab)
    local process_icons = {
        ["nvim"] = {
            { Foreground = { Color = "#A6E3A1" } },
            { Text = wezterm.nerdfonts.custom_vim },
        },
        ["vim"] = {
            { Foreground = { Color = "#A6E3A1" } },
            { Text = wezterm.nerdfonts.dev_vim },
        },
        ["zsh"] = {
            { Foreground = { Color = "#F38BA8" } },
            { Text = wezterm.nerdfonts.dev_terminal },
        },
        ["bash"] = {
            { Foreground = { Color = "#F38BA8" } },
            { Text = wezterm.nerdfonts.cod_terminal_bash },
        },
    }

    local process_name = string.gsub(
        tab.active_pane.foreground_process_name,
        "(.*[/\\])(.*)",
        "%2"
    )

    return wezterm.format(process_icons[process_name] or {
        { Foreground = { Color = "#89DCEB" } },
        { Text = string.format("[%s]", process_name) },
    })
end

local function get_current_working_dir(tab)
    local current_dir = tab.active_pane.current_working_dir
    local HOME_DIR = string.format("file://%s", os.getenv("HOME"))

    return current_dir == HOME_DIR and "  ~"
        or string.format(
            "  %s",
            string.gsub(current_dir, "(.*[/\\])(.*)/", "%2")
        )
end

wezterm.on("format-tab-title", function(tab)
    return wezterm.format({
        { Attribute = { Intensity = "Half" } },
        { Text = string.format(" %s  ", tab.tab_index + 1) },
        "ResetAttributes",
        { Text = get_process(tab) },
        { Text = " " },
        { Text = get_current_working_dir(tab) },
        { Foreground = { Color = "#000000" } },
        { Text = "  ▕" },
    })
end)

return {
    font_size = 15,
    use_fancy_tab_bar = false,
    adjust_window_size_when_changing_font_size = false,
    color_scheme = "Catppuccin Mocha",
}
```

### Expected Behavior

In an ideal world this shouldn't lag this much 😉

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by saurabhchardereal** [comment]
Finally got around testing it. While the delay has certainly gotten less noticeable but I still see a slight delay, although somewhat negligible.

I'd consider this issue fixed as the delay doesn't bother as much as before.

Thanks.

https://user-images.githubusercontent.com/51372520/213980810-a15598ed-6175-4d66-95e3-dcf0e8198271.mp4

**Comment by wez** [comment]
The main source of the delay is in interrogating the different processes to extract their process information.

Take a look at this new section in the docs: https://wezfurlong.org/wezterm/recipes/passing-data.html#passing-data-from-a-pane-to-lua

If you switch to using escape sequences to push the information to wezterm as user vars your custom tab formatting will run much faster.
