### ISSUE TITLE
`nvim-autopairs` doesn't work when `enable_kitty_keyboard` is `true`

### ISSUE THREAD

**Issue by musjj** [wez/wezterm#3315]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

 bspwm 0.9.10

### WezTerm version

20230321-122932-5a738446

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When `enable_kitty_keyboard` is set to `true`, the plugin [nvim-autopairs](https://github.com/windwp/nvim-autopairs) doesn't work. Oddly, this seems to happen only to round brackets. Square brackets are completed correctly.
I tried running nvim in kitty without any configs (not sure if the keyboard behaviour wezterm is emulating is on by default), and autopairs works just fine there.

### To Reproduce

1. Install `nvim-autopairs` in neovim and ensure it works
2. Set `enable_kitty_keyboard` to `true`
3. `nvim-autopairs` in neovim will stop working

### Configuration

```lua
return { enable_kitty_keyboard = true }
```

### Expected Behavior

`nvim-autopairs` should work.

**Comment by wez** [comment]
Please try the latest nightly build; a number of fixes to the kitty keyboard support have been made and may well have resolved this.

**Comment by musjj** [comment]
Tried the latest commit:
```
❯ wezterm --version
wezterm 20230408-200110-397593be
```
Unfortunately, the issue still occurs. Any way to debug what's going on here?

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues has information on troubleshooting keyboard issues. Please enable debug_key_events and include the logs from pressing the keys that aren't working.

Please also capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by musjj** [comment]
Without `enable_kitty_keyboard`:
```
23:16:20.449  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(Quote), modifiers: SHIFT, phys_code: Some(Quote), raw_code: 48, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:16:20.449  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('"'), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Quote), modifiers: SHIFT, phys_code: Some(Quote), raw_code: 48, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:16:20.449  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('"') mods=Modifiers(NONE | SHIFT)
23:16:20.449  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\"", Char('"') Modifiers(NONE | SHIFT)
23:16:20.633  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('"'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Quote), modifiers: SHIFT, phys_code: Some(Quote), raw_code: 48, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:16:20.633  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('"') mods=Modifiers(NONE | SHIFT)
23:16:20.913  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
```

With `enable_kitty_keyboard`
```
23:14:01.446  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(Quote), modifiers: SHIFT, phys_code: Some(Quote), raw_code: 48, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:14:01.446  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('"'), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Quote), modifiers: SHIFT, phys_code: Some(Quote), raw_code: 48, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:14:01.446  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('"') mods=Modifiers(NONE | SHIFT)
23:14:01.446  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[34;2u", Char('"') Modifiers(NONE | SHIFT)
23:14:01.593  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('"'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Quote), modifiers: SHIFT, phys_code: Some(Quote), raw_code: 48, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:14:01.593  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('"') mods=Modifiers(NONE | SHIFT)
23:14:01.808  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
```

It seems the problem is revealed in `wezterm_term::terminalstate::keyboard`. Without `enable_kitty_keyboard`, wezterm sends `"\""`, with it enabled wezterm sends `"\u{1b}[34;2u"`

I don't think a terminal recording is necessary now, but do tell if you still need it anyways.

**Comment by wez** [comment]
I'd appreciate the recording because it will capture the kitty protocol mode that nvim is asking for.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by musjj** [comment]
Thanks for the quick fix! But it looks like there's still a problem for round brackets:

```
04:42:04.456  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(K9), modifiers: SHIFT, phys_code: Some(K9), raw_code: 18, repeat_count: 1, key_is_down: true, handled: Handled(false) }
04:42:04.456  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('('), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K9), modifiers: SHIFT, phys_code: Some(K9), raw_code: 18, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
04:42:04.456  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('(') mods=Modifiers(NONE | SHIFT)
04:42:04.456  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[40;2u", Char('(') Modifiers(NONE | SHIFT)
04:42:04.567  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('('), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K9), modifiers: SHIFT, phys_code: Some(K9), raw_code: 18, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
04:42:04.567  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('(') mods=Modifiers(NONE | SHIFT)
04:42:04.903  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftShift, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
04:42:04.903  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=LeftShift mods=Modifiers(0x0)
```

Here's the recording:

[wezterm-recording-y2TLtZ.cast.txt](https://github.com/wez/wezterm/files/11186377/wezterm-recording-y2TLtZ.cast.txt)

**Comment by musjj** [comment]
It looks like it's a problem for all num symbols (`!@#$%^&*()`)
[wezterm-recording-WcYV4R.cast.txt](https://github.com/wez/wezterm/files/11186386/wezterm-recording-WcYV4R.cast.txt)

**Comment by wez** [comment]
I made another run at it in the latest `main`!

**Comment by musjj** [comment]
Thanks, it seems to work great for me!
