### ISSUE TITLE
Mouse selection grabs previous char too easy

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#350]
## Describe the bug

Not even sure if this is a bug, but definitely feels weird. Will try to explain:

If you want to select text with mouse, normally terminals (or even web browsers) give you a little bit of tolerance. For example if you'd like to copy **doring** from the word **Vendoring**, and you start clicking to select at the red-marked place:

![image](https://user-images.githubusercontent.com/307899/100064461-d8794200-2e32-11eb-8284-dc17a6c8154b.png)

most terminals start the selection from the letter **d**, wezterm seems to start from **n**.

Sorry if there is a configuration parameter about this that I've missed or this is the intended behavior. Just felt weird and selecting something took longer so I wanted to report.

## Environment:

 - OS: Linux X11
 - Version: `wezterm 20201101-103216-403d002d-62-geee40f7d`

**Comment by wez** [comment]
I think that's a fair request.  Right now wezterm divides the mouse coordinates by the cell size to determine which cell is selected, so that math biases to the left/top.  I think it's reasonable to round that to the nearest cell edge to decide this.

**Comment by wez** [comment]
This should be fixed now in the nightly build

**Comment by seqizz** [comment]
Yep, works OK now. Thanks :+1:

**Comment by yangit** [comment]
Somehow it is still broken for me on version 20210814-124438-54e29167.
[Here is the video](https://www.dropbox.com/s/zu4vtmon2mn68qh/bug.mov?dl=0)

**Comment by yangit** [comment]
I'm on mac Big Sur 11.4

**Comment by wez** [comment]
Please file a new issue of your own!
