### ISSUE TITLE
Num lock as a modifier

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#3514]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

AwesomeWM

### WezTerm version

commit b5c7374f4bdb1b387f1db8053695ae6f81088c27

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

After last upgrade using open_with does not work as expected. Pressing a key on the overlay screen with shortcuts shows this on debug log:

```
15:35:43.171  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Char('a'), modifiers: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NUM_LOCK, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
```

So it thinks NUM_LOCK is a valid modifier to 'a' key. Esc to exit the overlay did not work, which I assume because of the same reason (it saw numlock+Esc which wasn't valid).

When I toggled numlock to "off" (via numlockx tool) it worked.

### To Reproduce

Use the configuration below with your numlock "on" and try to click a link

### Configuration

```
    -- Alt-c to "click" links without mouse
    {
      key = 'c',
      mods = 'ALT',
      action = wezterm.action.QuickSelectArgs {
        label = 'open url',
        patterns = {
          'https?://\\S+',
        },
        action = wezterm.action_callback(function(window, pane)
          local url = window:get_selection_text_for_pane(pane)
          wezterm.log_info('opening: ' .. url)
          wezterm.open_with(url)
        end),
      },
    },
```

### Expected Behavior

Numlock should not be valid modifier for alphabetical keys (arguably also numbers? since toggling numlock in a numpad won't allow you to type the number, why should we allow one to define "non-numlock 4" in the config :thinking:). Still, I am probably missing something more complex.

### Anything else?

Thanks for the effort! 🚀

**Comment by wez** [comment]
Should have been resolved by https://github.com/wez/wezterm/commit/eaab3d08aefd3eff92a49499d903586c316f83a8
The intent was not to allow you to use num lock as a key binding modifier, but to pass through that state for the kitty keyboard protocol.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by seqizz** [comment]
Either I did something wrong while compiling or it didn't solve the issue. Couldn't make it work with numlock on with commit 0abc28dae05c3da567cdd3ffec8398f3a1b4c113. Later I'll try again with nightly builds to be safe.

**Comment by wez** [comment]
Hmm, try with 9b1321fac11c2bbae87aadcb9b486ce12e5f1e18

**Comment by seqizz** [comment]
Sadly, still no joy with 9f9e330dcda0b6956ca659a71b55ec9683480d86
```
22:16:39.547  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Char('a'), modifiers: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NUM_LOCK, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
```
I can run a trace or similar if something would help.

**Comment by wez** [comment]
Should really be resolved now in `main`

**Comment by seqizz** [comment]
Yup, looks OK now. Thanks again!
