### ISSUE TITLE
Shift doesn't work in debug mode

### ISSUE THREAD

**Issue by Drllap** [wez/wezterm#3521]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230411-221643-c8b8e811

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The _Debug Overlay_ doesn't take as `Shift` as input, as in `Shift+9` should type `(` in the REPL but nothing happens

### To Reproduce

* I run wezterm with no configuration, `wezterm -n` (the `-n` wasn't required just wanted to make sure this didn't have something to do with my config)
* press `CTRL-SHIFT-l` to open up the _Debug Overlay_
* press `SHIFT-9`
* nothing happes

### Configuration

N/A, this also happens when using the `-n` flag

### Expected Behavior

`(` should appear in the REPL

**Comment by Drllap** [comment]
Also, `CTRL` doesn't appear to work either, I can't close the _Debug Overlay_ with `CTRL-D`

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Drllap** [comment]
Just tried this on wezterm 20230418-150623-db720bd7 and this isn't fixed.

Also I can no longer use `ESC` to close the _Debug Overlay_

**Comment by wez** [comment]
> Edit: `ESC` doesn't work if there are any other chars in the prompt line, but it does work if I erase everything from the prompt line first.

That's intended behavior.

I can't reproduce the issue with shift on linux or mac.
