### ISSUE TITLE
Top level split break terminal size

### ISSUE THREAD

**Issue by zasdaym** [wez/wezterm#4686]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Maximize the wezterm window and then try to run `wezterm cli split-pane --top-level` multiple times, the terminal size will be broken.

Before
<img width="1512" alt="Screenshot 2023-12-15 at 13 55 16" src="https://github.com/wez/wezterm/assets/18226580/831a45b4-a04f-4312-b407-d6cbea6352ef">

After
<img width="1512" alt="Screenshot 2023-12-15 at 13 56 00" src="https://github.com/wez/wezterm/assets/18226580/51570caa-8eda-4844-a049-e881f653bbf3">

### To Reproduce

Maximize the wezterm window and then try to run `wezterm cli split-pane --top-level` multiple times, the terminal size will be broken.

### Configuration

no config

### Expected Behavior

Terminal size not broken

**Comment by wez** [comment]
Please try the latest nightly; I think this may have been resolved as part of 8f74e1c8486d66f40bd1d11cd01160774df64b07

**Comment by zasdaym** [comment]
<img width="1512" alt="Screenshot 2024-02-03 at 18 15 31" src="https://github.com/wez/wezterm/assets/18226580/274f3cdc-fe19-43a9-8f27-f7edc19ebfd2">
Still the same.
