### ISSUE TITLE
[Bug]: Noticable delay on split pane navigation

### ISSUE THREAD

**Issue by mister-choo** [wez/wezterm#6436]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

DE: GNOME 46.0
WM: Mutter

### WezTerm version

wezterm 20241119-101432-4050072d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Navigating from nvim pane to wezterm pane happens with about 2 sec delay

### To Reproduce

nvim config
```lua
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme! it makes testing nicer
  'folke/tokyonight.nvim',
  'mrjones2014/smart-splits.nvim',
  -- add any other pugins here
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

require('smart-splits').setup({
  -- add any options here
})

vim.keymap.set('n', '<C-Left>', require('smart-splits').move_cursor_left)
vim.keymap.set('n', '<C-Down>', require('smart-splits').move_cursor_down)
vim.keymap.set('n', '<C-Up>', require('smart-splits').move_cursor_up)
vim.keymap.set('n', '<C-Right>', require('smart-splits').move_cursor_right)

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme! it makes testing nicer
vim.cmd([[colorscheme tokyonight]])
```

### Configuration

wezterm config:
```lua
local wezterm = require 'wezterm'
local config = {}
if wezterm.config_builder then
    config = wezterm.config_builder()
end

local function is_vim(pane)
    return pane:get_user_vars().IS_NVIM == 'true'
    -- return false
end

local direction_keys = {
    LeftArrow = 'Left',
    DownArrow = 'Down',
    UpArrow = 'Up',
    RightArrow = 'Right',
}

config.leader = { key = "a", mods = "CTRL" }

local function split_nav(key)
    return {
        key = key,
        mods = 'CTRL',
        action = wezterm.action_callback(function(win, pane)
            if is_vim(pane) then
                win:perform_action({ SendKey = { key = key, mods = 'CTRL' }, }, pane)
            else
                win:perform_action({ ActivatePaneDirection = direction_keys[key] }, pane)
            end
        end),
    }
end

config.keys = {
    {
        key = "v",
        mods = "LEADER",
        action = wezterm.action { SplitHorizontal = {
            domain = "CurrentPaneDomain" } }
    },
    split_nav('LeftArrow'),
    split_nav('RightArrow'),
    split_nav('DownArrow'),
    split_nav('UpArrow'),
}

return config
```

### Expected Behavior

Navigation from wezterm pane to nvim pane to take the same amount of time as from nvim pane to wezterm

### Logs

There is no output

**Comment by mister-choo** [comment]
Made a good effort to find an existing issue, but looks like there isn't one. In smart-splits discussions on the topic it was suggested that some of the wezterm cli operations can be slow, which causes this.

**Comment by mister-choo** [comment]
Investigated this some more and looks like it's a problem with fish:
$ time wezterm cli activate-pane-direction Right
________________________________________________________
Executed in  122.03 millis    fish           external
   usr time    3.97 millis  439.00 micros    3.53 millis
   sys time   13.34 millis   79.00 micros   13.26 millis

In different shells there isn't a delay and time command add some strange time which isn't usr or sys time

**Comment by mister-choo** [comment]
After I fixed startup time on fish command started executing in more manageable 4 millis. Why could that be the case? It seems shell startup time affects the wezterm cli time, even if it was started as a subprocess

**Comment by jeeeem** [comment]
> After I fixed startup time on fish command started executing in more manageable 4 millis. Why could that be the case? It seems shell startup time affects the wezterm cli time, even if it was started as a subprocess

Does it still happening to you? I have this issue for a long time, and i thought its bcos im using Windows. I cant find anyone who has a similar issue with this slowness.

**Comment by midgramr** [comment]
I'm still having this issue, which is hard to reproduce. Starting up a new instance of wezterm seems to fix the slowness for a while, but it always comes back. I've noticed the slowness with fish and zsh but not bash
