### ISSUE TITLE
Problems with tiling on gnome (wayland

### ISSUE THREAD

**Issue by jpluomajoki** [wez/wezterm#6633]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

mutter (on gnome)

### WezTerm version

20250202_002357_1757ef2b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

There are multiple issues with using wezterm on gnome 47.3 (fedora 41). If wayland is enabled, there is no way to use the tiling feature (having two windows side by side) without issues. I am talking about the default tiling feature, which enables using two windows side by side.

If `window_decorations` are set to `NONE` or not at all, resizing does not work properly, instead the window is forces to half of the width of the screen. On the other hand, if `window_decorations` are set to something other, such as `RESIZE` or `RESIZE | INTEGRATED_BUTTONS | TITLE`, a non-native looking top bar appears and the bottom of the window overflows from the bottom, meaning I cannot see my terminal prompt or nvim statusline etc.

### To Reproduce

case 1. On gnome 41 with wayland, with empty wezterm configuration (or with `window_decorations` set to `NONE` or default), tile a wezterm instance and another window side-by-side with SUPER-left and SUPER-right. Try to resize the windows by dragging the middle or with SUPER+right mouse drag. When trying to resize from wezterm, nothing happens and when resizing the other window, wezterm moves but does not change size. 
case 2. With wezterms `window_decorations` set to anything other than `NONE` or default, do the same. This time resizing works, but bottom of the terminal is hidden from view.
These both have been tested with two monitors, 34" 3440x1440 and 14" 1920x1200.
with `enable_wayland = false`, both of these cases work as expected with windows resizing and nothing overflowing, though it seems to cause performance issues when one instance is used for long times (two working days, suspending in between), which is likely a separate issue caused by xwayland or something else outside the scope of this issue.

### Configuration

`config.window_decorations = 'NONE'`
or 
`config.window_decorations = 'RESIZE'`
or
`config.window_decorations = 'TITLE | RESIZE'`

### Expected Behavior

Resizing tiled windows works as expected even with window_decorations disabled and window size is set correctly when window decorations are used.

### Anything else?

I believe I found the line that causes the first issue I mentioned, where when the tiled window is resized, it's width is forced to be half of the window's size. In here https://github.com/wez/wezterm/blob/b28bbbc4c8345197e433590c9ce50a7bf3ea5bc7/window/src/os/wayland/window.rs#L1298-L1307
the `suggested_bounds` seems to always equal the size of the screen (minus the top bar of gnome), e.q on my monitor 3440 x 1408.
I tried to modify and build it, and with using `configure.new_dimensions`, I was able to make it a bit better but caused other issues. I'll give it another go later, but as I'm not too experienced with either rust or GUI programming, I'm not expecting to get far by myself. Mainly wayland seems to send a new event with the dimensions before it was tiled when the window is unfocused for the first time after sending it to a split view.

I'm also unsure whether the different `STCWindowState::TILED_XXX` values work exactly the way the code seems to expect them to work. 
When a window is tiled on the right gnome, the window state is `TILED_UP | TILED_BOTTOM | TILED_RIGHT`. I read the code as assuming that only one of the `TILED_XXX` values are active at a time, but actually almost always at least two are active, and with the limited tiling functionality on gnome, three are always active.

**Comment by aliaksandr-trush** [comment]
This issue was fixed in https://github.com/wezterm/wezterm/pull/6545

**Comment by jpluomajoki** [comment]
Amazing, thanks @aliaksandr-trush! Built the latest `main` and resizing works perfectly. With `WINDOW_DECORATIONS = "RESIZE"` there is still an issue with the window overflowing on the bottom, but that's a non-issue for me personally.
