### ISSUE TITLE
inconsistent terminal size on startup with tiling window manager

### ISSUE THREAD

**Issue by Comradin** [wez/wezterm#695]
## Describe the bug

When I start wezterm the first time the window fills my screen but the actual size of the terminal inside is 80x24 as back in the days when I had a serial terminal. I use i3 as window manager, so its always started in maximized form.

## Environment (please complete the following information):

 - OS: ArchLinux, i3
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name: LANG=de_DE.UTF-8

## To Reproduce

I start a first wezterm on an empty i3 workspace. wezterm starts and draws its window to the whole screen.
Now checking with `tput cols` and `tput lines` I get 80x24 as the actual size of the terminal inside the application window.

When I start a second instance of wezterm on that i3 workspace or a different program, so that the wezterm application gets resized to half of the screen these values change to the correct values. For example for my FullHD monitor and chosen font and sizes this will be 95x45. This happens too, when I move the window to a different workspace.

Looks like the program isn't able to identify the actual size of the screen when forced into maximum display by the tiling window manager?

## Configuration

Nothing special here, just a color scheme:

```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono"),
  color_scheme = "MaterialDark",
}
```

## Expected behavior

Start with maximum available columns and lines, not sure how to phrase it.

## Screenshots

Just for completeness here tty and term on a fresh (reduced) instance:
```
❯ echo $(tty) TERM=$TERM with ${COLUMNS}x${LINES}
/dev/pts/0 TERM=xterm-256color with 80x24
```

I made a screenshot of a fresh window with vi and the config, this shows the startup behavior best.

![2021-04-15-072320_1920x1058_scrot](https://user-images.githubusercontent.com/4760546/114818190-a2c1ff00-9dbb-11eb-8c30-57dceea4d7f1.png)

## Additional context

when I toggle the terminal window into floating mode in i3 the actual size of the window gets reduced to the mentioned 80x24 lines. Doing this with my browser window I am typing this report in right now, the browser window size is still quite close to the screen resolution.

![2021-04-15-073046_989x674_scrot](https://user-images.githubusercontent.com/4760546/114818791-ac983200-9dbc-11eb-84a9-261c4ccb3731.png)

Rezising this window will change the lines and columns and when toggling back from floating to tiling maximize the terminal has the expected amount of lines and columns.

**Comment by wez** [comment]
I wonder if wezterm is confused about whether it is in full screen mode in that situation.  I'll see if I can reproduce this in the morning.  If you press `ALT-Enter` that will tell wezterm to toggle fullscreen mode. I wonder if doing that twice will make it pick up the correct size as a workaround until this is fixed?

I don't know if this is related, but I'd recommend setting setting this when using a tiling window manager:

```lua
  adjust_window_size_when_changing_font_size = false
```

(https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html)

**Comment by wez** [comment]
Hmm, I couldn't reproduce this, so I suspect that an important element is missing.
I ran:

* `Xephyr :2 -screen 1024x768` to setup an Xserver for testing
* `DISPLAY=:2 i3` to start i3 on that server
* `DISPLAY=:2 WEZTERM_LOG=window=trace,wezterm_gui::termwindow=trace,info wezterm` - to log relevant window/sizing information

For me, the window does immediately get resized to fill the screen.

I'd like you to try two things:

* Please upgrade to the nightly release: there's some additional code in that build to detect to DPI changes under X11 and that *may* help with this case
* If it still isn't working, can you adjust your i3 config so that wezterm is spawned as: `WEZTERM_LOG=window=trace,wezterm_gui::termwindow=trace,info wezterm 2>>/tmp/wezterm.txt` then start wezterm to reproduce the issue, then capture `/tmp/wezterm.txt` and get that file to me.

**Comment by Comradin** [comment]
Thanks for the quick response.

I tried to set the adjust_window.. setting you suggested, that did not change the behavior. A fresh first wezterm instance appeared without full usage of columns and lines. But the `ALT-Enter` workaround is quite a helper.

Ill do the i3 config adjustments later today and report back to you.

**Comment by Comradin** [comment]
Sorry for the late response, I failed to take the time to create the suggested log file until today. As an excuse I could say the alt+enter workaround worked like a charm.

For the logfile actions, I started wezterm with the mentioned options. There will be some mouse events in the log and I issued `tput cols` and `tput lines` and in the end I moved the window to a different workspace where lines and columns got set to the correct value.

[wezterm.txt](https://github.com/wez/wezterm/files/6413010/wezterm.txt)

**Comment by wez** [comment]
The most significant lines from the log are:

```
 2021-05-03T05:42:26.683Z TRACE wezterm_gui::termwindow         > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 0, pixel_height: 0, dpi: 120 } is_full_screen:false
 2021-05-03T05:42:26.683Z TRACE wezterm_gui::termwindow         > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 3834, pixel_height: 2113, dpi: 120 } is_full_screen:false
 2021-05-03T05:42:26.740Z TRACE wezterm_gui::termwindow::resize > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 800, pixel_height: 550, dpi: 120 }
 2021-05-03T05:42:26.740Z TRACE wezterm_gui::termwindow::resize > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 800, pixel_height: 550, dpi: 120 }
 2021-05-03T05:42:26.740Z TRACE wezterm_gui::termwindow         > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 3834, pixel_height: 2113, dpi: 120 } is_full_screen:false
 2021-05-03T05:42:26.758Z TRACE wezterm_gui::termwindow         > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 3834, pixel_height: 2113, dpi: 120 } is_full_screen:false
 2021-05-03T05:43:56.220Z TRACE wezterm_gui::termwindow           > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 1914, pixel_height: 1033, dpi: 120 } is_full_screen:false
 2021-05-03T05:43:56.247Z TRACE wezterm_gui::termwindow           > resize event, current cells: RowsAndCols { rows: 45, cols: 191 }, new dims: Dimensions { pixel_width: 1914, pixel_height: 1033, dpi: 120 } is_full_screen:false
```

I think what's needed is some awareness of when the window sizes that wezterm requests are not being respected by the window manager, and then to adjust/revise strategy if not.

**Comment by bew** [comment]
Could you do it lazily?
Where you would ask the WM to resize your window, but do not resize it yet, and then the WM does resize it I'm guessing you'd get an event for that and you can react to the size change? (and not react at all if the size doesn't actually change like it can happen with HerbstluftWM)

**Comment by chaoyi** [comment]
I have the same issue with bspwm tiling window manager.  When wezterm is spawn in a tile, the terminal size is fixed at 80x24.   The issue only happens with non default dpi.  I changed dpi back to 96 with `echo Xft.dpi: 96 | xrdb -merge` then wezterm is spawn with correct rows and cols.

log with dpi 192
```
 2021-06-29T22:28:41.483Z TRACE wezterm_gui::termwindow::resize > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 2140, pixel_height: 1692, dpi: 192 } is_full_screen:false
 2021-06-29T22:28:41.503Z TRACE wezterm_gui::termwindow::resize > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 1240, pixel_height: 908, dpi: 192 }
 2021-06-29T22:28:41.552Z TRACE wezterm_gui::termwindow::resize > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 2140, pixel_height: 1692, dpi: 192 } is_full_screen:false
```

log with dpi 96
```
 2021-06-29T22:30:13.223Z TRACE wezterm_gui::termwindow::resize > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, new dims: Dimensions { pixel_width: 2140, pixel_height: 1692, dpi: 96 } is_full_screen:false
```

**Comment by MuhammedZakir** [comment]
I am gettting a somewhat similiar behavior to @chaoyi when spawning tabs, but only when I use the cli. I don't have this problem if I use keyboard shortcut(`Ctrl+Shift+T`) to create a new tab. 

```
$ wezterm cli spawn
1

# go to new tab
$ tput lines
24
$ tput cols
80
```

I am getting this regardless of window size, or layout (float/tile).

![wezterm_spawn_window_error](https://user-images.githubusercontent.com/8190126/124231631-2626fd00-db2e-11eb-8f0d-7b890bb3eff0.png)

**Comment by wez** [comment]
@MuhammedZakir that doesn't seem related to this issue; please file a separate issue!

**Comment by wez** [comment]
Github accidentally interpreted my commit message as this being resolved, which it isn't.

**Comment by wez** [comment]
I just pushed a couple of commits that make wezterm aware of whether the window is in a state where its size is constrained in some way (eg: maximized in some axis under X11 or Wayland, or has an edge in a tiled state under Wayland).
In that state wezterm won't try to change the window size, and it should be a bit better at figuring out the initial size.

Those commits will show up in the nightly builds within about 30 minutes from now.  I'd appreciate it if you could give that a try when you have a few moments this weekend and let me know how well it works for you.

**Comment by chaoyi** [comment]
For me the terminal size issue was gone for quite some time and I have been using wezterm happily.   However, I just tried the latest version and the issue came back :(.  The last commit that works is `6a7e6596`.  BTW, I use bspwm and X11.

**Comment by gksudolol** [comment]
Yes same as chaoyi, I would say the commits from the last day or 2 the issue began for me. Rebuilt from main with no change

**Comment by wez** [comment]
I think I made this better(er).  Please let me know how you get on with the latest nightly!

**Comment by gksudolol** [comment]
Can confirm this is fixed in the nightly, thank you

**Comment by chaoyi** [comment]
No luck for me.  Still have the issue.

**Comment by wez** [comment]
@chaoyi thanks for those logs; I think `main` will do a bit better at handling that case!

**Comment by chaoyi** [comment]
After `9617c74`, seems resize is correct but scaling is incorrect (font too small).

**Comment by wez** [comment]
@chaoyi you shouldn't need to change anything in your config.  I've pushed another commit; maybe this one does it all?

**Comment by chaoyi** [comment]
Yes, this one works.

**Comment by wez** [comment]
Thanks for confirming!

**Comment by MuhammedZakir** [comment]
After this fix, in tiling mode, initial size of a new tab created using `Ctrl+Shift+T` is `80x24`. Floating and tiling it again, or resizing the window fixes this. After doing this once, newly created tabs for that window get correct/current size.
