### ISSUE TITLE
Can't type brackets {} or backslash \ on my norwegian keyboard

### ISSUE THREAD

**Issue by erf** [wez/wezterm#760]
## Describe the bug

Similar to #158 i can't seem to type brackets {} or backslash \ anymore. When typing the key combo nothing happens.

Not sure when this happened.. 🤔

Running the RUST_LOG command i get a *ding* when typing these symbols:

```
 RUST_LOG=trace /Applications/WezTerm.app/Contents/MacOS/wezterm
 2021-05-04T12:16:01.874Z INFO  wezterm_mux_server_impl::local > setting up /Users/erlend/.local/share/wezterm/gui-sock-15911
 2021-05-04T12:16:01.956Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Apple M1 4.1 Metal - 71.5.9 is_context_loss_possible=false wezterm version: 20210503-093429-7be475ef
 2021-05-04T12:16:11.726Z INFO  wezterm_gui::frontend          > Ding! (this is the bell)
 2021-05-04T12:16:12.581Z INFO  wezterm_gui::frontend          > Ding! (this is the bell)
 2021-05-04T12:16:12.581Z INFO  wezterm_gui::frontend          > Ding! (this is the bell)
 2021-05-04T12:16:23.496Z INFO  wezterm_gui::frontend          > Ding! (this is the bell)
```

## Environment (please complete the following information):

 - OS: macOS 11.3.1 (20E241)
 - Version: wezterm 20210503-093429-7be475ef
 - Norwegian keyboard layout

## To Reproduce

Run wezterm. Type: `{}\`

Key combo on my mac for brackets is `SHIFT-OPTION-8` or `SHIFT-OPTION-9`

And for backslash `SHIFT-OPTION-7`

## Configuration

```
local wezterm = require 'wezterm'

return {
	use_ime = true,

	send_composed_key_when_left_alt_is_pressed = true,
	send_composed_key_when_right_alt_is_pressed = true,
}
```

It was the same with these variables set to `false`.

## Expected behavior

I would except typing the brackets/backslash key combo would produce a bracket/backslash, but it does nothing.

**Comment by achimnol** [comment]
I have the same issue when enabled IME.
https://github.com/wez/wezterm/issues/615#issuecomment-828600729

**Comment by erf** [comment]
Sorry to bother you, but there is no easy fix to this issue you think? wezterm in this state is not very usable for me, i could roll back but i'd like to keep up-to-date with the features :)

**Comment by wez** [comment]
@erf sorry; the main constraint is having the right mix of time to investigate and creativity to come up with a resolution.

**Comment by erf** [comment]
@wez no worries. Take your time.

**Comment by erf** [comment]
Maybe [this](https://github.com/kovidgoyal/kitty/blob/f787a377c3a32563cef19c603ff0ec76eedcfb46/docs/keyboard-protocol.rst) can help in figuring out the keyboard issue. The Kitty creator seem to be working on a keyboard protocol.

**Comment by kar1** [comment]
I think it's related to the Input Method Editor. I'm on Debian with a Danish keyboard layout without these issues. The new Kitty keyboard protocol is based on www.leonard.org/hacks/fixterms/ which Wezterm implements with the `enable_csi_u_key_encoding = true' setting. Maybe worth a try setting it and disable ime for now.

**Comment by erf** [comment]
@kar1 tried it, but did not work. Same result

**Comment by wez** [comment]
FWIW, this issue is about getting the correct keyboard information out of macOS, rather than about how it is encoded and sent to the application in the terminal.

**Comment by erf** [comment]
Maybe this could help? 

https://github.com/gnachman/iTerm2/blob/master/sources/iTermKeyboardHandler.h
https://github.com/gnachman/iTerm2/blob/master/sources/iTermKeyboardHandler.m

**Comment by arnaudlimbourg** [comment]
Similar issue on French keyboards, most likely for the same reason.

**Comment by wez** [comment]
Thanks to the groundwork laid in https://github.com/wez/wezterm/issues/1483 I just pushed a commit that fixes this issue for me.  It will show up in the nightly downloads within an hour.

**Comment by erf** [comment]
Awesome! 

This let's me press press `shift+789` to produce `/()` and `shift-leftOption+789` to produce `\{}`

I still can't press `leftOption+789` to produce `|[]` etc. on my Norwegian Macbook keyboard.

**Comment by wez** [comment]
`ALT-<number>` by default switches to a tab in that position; you'll need to do this to remove just those assignments:

```lua
return {
  keys = {
    -- in "phys:7" means "the key in the same physical position as 7 in an ANSI standard US keyboard"
    {key="phys:7", mods="ALT", action="DisableDefaultAssignment"},
    {key="phys:8", mods="ALT", action="DisableDefaultAssignment"},
    {key="phys:9", mods="ALT", action="DisableDefaultAssignment"},
  }
}
```

**Comment by erf** [comment]
This is no longer working as mentioned [here](https://github.com/wez/wezterm/issues/1706#issuecomment-1065997142)

**Comment by wez** [comment]
Should hopefully be fixed again now!

**Comment by erf** [comment]
Working :) Thank you
